args <- commandArgs(TRUE)
s <- read.table(args[1])
pdf(paste(args[1],"-time.pdf",sep=""))
barplot(s$V1, xlab="Applications", ylab="Time")
pdf(paste(args[1],"-sys-call-count.pdf",sep=""))
getOption("scipen")
opt <- options("scipen" = 20)
getOption("scipen")
barplot(s$V2, xlab="Applications", ylab="System call count", ylim=c(0,1200000))
