args <- commandArgs(TRUE)
s <- read.table(args[1])
pdf(paste(args[1],"-time.pdf",sep=""))
barplot(s$V1, xlab="Applications", ylab="Time")
pdf(paste(args[1],"-sys-call-count.pdf",sep=""))
barplot(s$V2, xlab="Applications", ylab="System call count")
